# Mongoid Configuration for MongoLab on Heroku
# ===========================================
#
# Copy this file to config/mongoid.yml,
# commit it to your repo, then push to heroku.

production:
  uri: <%= ENV['MONGOLAB_URI'] %>

development:
  sessions:
    default:
      database: errbit_development
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
    use_utc: true

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: errbit_test
  options:
    identity_map_enabled: true
    use_utc: true
